= Setup

== (java) backend

The java backend rests in the `./backend` folder and consists of several projects.

The first one is the `webapp-api` one, which contains the code for the webapp to interact with our business logic.
The application itself is a spring boot application.

=== Build details

The management of dependencies and co. is done using _gradle kotlin_.
This means that all dependencies, gradle tasks and co. are set up through it.
As it is a bit complicated when you're not used to it, this part is a short summary of the setup.

In the root of the project, we have the `settings.gradle.kts` (.kts being the kotlin ending).
This file can define many things, but for our current use case it is limited to defining the project name, as well as which folders to include and search through for further _gradle tasks_.
Gradle tasks are pre-setup commands that run defined functions, for example the `build` command for `java` tasks.

To enable this, we have several helper files and folders.
These are, in the root directory of the project, the `gradlew` and `gradlew.bat` files, which allow you to call and execute gradle commands in your terminal using
`./gradlew <command>`, i.e. `./gradlew build`.
For this to work, there is also the directory `gradle/wrapper/`
that contains anything required to run this.

Each project imported included in the `settings.gradle.kts` file has to contain a `build.gradle.kts` file.
This file defines various things, like plugins to use, dependencies as well as tasks.
In our setup, the file
`backend/build.gradle.kts` has multiple jobs.

- Defines allowed plugin versions
- Defines for all subprojects (more on this further down)
* To automatically use the `java` plugin
* Which java version is used
* Pins versions of plugins
* Pins versions of dependencies
* The repositories where dependencies can be fetched
* The main package for the *.jar
* Modifiers for tasks (i.e. that tasks with type `test` should use the `junit-plattform`)

A subproject is basically and directory below this one, that also contains a `build.gradle.tks` file.
The file `backend/webapp-api/build.gradle.kts` contains the specific dependencies that are used in this service.
Hence we do not have to use all dependencies defined in the parent, but only what we need.
As you can also see, we don't need to specifically apply the `java` plugin, as the parent already defines that we use it.

=== Commands

The following gradle commands can be run from the terminal, once you're in the root folder of the project:

- `./gradlew test` -> runs all tests in the backend service
- `./gradlew build` -> builds the backend
- `./gradlew bootRun` -> locally run the spring application

Whilst right now, there is only one backend service, in the case more are added, you can specify which you want to run with the following command:

`./gradlew backend:<service-name>:<command>`

So you can only run the spring application you're interested in.

Additional information:

When running the application locally with `/gradlew bootRun`, you can access the openAPI spec via http://localhost:8080/api/v3/api-docs.
Beware that it's basic JSON, but you should be able to download it and generate code (i.e. for frontend) from it.

[NOTE]
====
If you're using intelliJ and import the gradle config (it should ask you automatically), you can select the specific tasks to run from your gradle view.
====
