ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Context and Scope

=== Business Context


ifdef::env-github[]
:MERMAID: source, mermaid
endif::[]
ifndef::env-github[]
:MERMAID: mermaid
endif::[]

[{MERMAID}]
....
graph TB
    Pyro["Pyro Platform"]

    subgraph "Customer Side"
        CustomerDev["Customer Developper"]
        CustomerMaintainer["Customer Maintainer"]
    end
    

    subgraph "Customer Side Extern"
        CustomerUser["Customer User"]
    end

    CustomerDev --> |"adds features"| Pyro
    CustomerMaintainer --> |"creates feature sets"| Pyro
    CustomerMaintainer --> |"assigns feature sets for users"| Pyro
    CustomerUser --> |"saves preferences"| Pyro
....

**<optionally: Explanation of external domain interfaces>**

=== Technical Context


ifdef::env-github[]
:MERMAID: source, mermaid
endif::[]
ifndef::env-github[]
:MERMAID: mermaid
endif::[]

[{MERMAID}]
....
graph TB
    subgraph "Pyro"
        PyroDashboard["Dashboard"]
        PyroAPI["API"]
    end

    subgraph "Customer Side"
        CustomerBackend["Customer Backend"]
    end
    

    subgraph "Customer Side Extern"
        CustomerClient["Customer Client"]
    end

    CustomerBackend --> |"fetches backend feature set"| PyroAPI
    CustomerBackend --> |"fetches user feature sets"| PyroAPI
    CustomerBackend --> |"updates user feature sets"| PyroAPI
    CustomerClient --> |"fetches user set"| PyroAPI
    CustomerClient --> |"saves user preferences"| PyroAPI
....

**<optionally: Explanation of technical interfaces>**

**<Mapping Input/Output to Channels>**
